{
 "title": "CHECKURL_",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "ActiveURLs",
    "label": "Active URLs",
    "query": {
     "query": "label_values(curl_check_success_, url)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "TOTAL %UP",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(curl_check_success_{url=~\"$ActiveURLs\"}[$__range])) / sum(count_over_time(curl_check_success_{url=~\"$ActiveURLs\"}[$__range]))",
     "legendFormat": "{{url}}"
    }
   ]
  },
  {
   "title": "TIME LAPSE",
   "type": "status-history",
   "gridPos": { "h": 19, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "curl_check_success_{url=~\"$ActiveURLs\"}",
     "legendFormat": "{{url}}"
    }
   ]
  },
  {
   "title": "%UP",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum_over_time(curl_check_success_{url=~\"$ActiveURLs\"}[$__range]) / count_over_time(curl_check_success_{url=~\"$ActiveURLs\"}[$__range])",
     "legendFormat": "{{url}}"
    }
   ]
  },
  {
   "title": "% TIME UP",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "expr": "sum_over_time(curl_check_success_{url=~\"$ActiveURLs\"}[$__range]) / count_over_time(curl_check_success_{url=~\"$ActiveURLs\"}[$__range]) * 100",
     "legendFormat": "{{url}}"
    }
   ]
  }
 ]
}